language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - asdf plugin-add aws-iam-authenticator ./
  - asdf list-all aws-iam-authenticator
  - asdf plugin-test aws-iam-authenticator ./ 'aws-iam-authenticator version' --asdf-tool-version 0.4.0-alpha.1
  - asdf plugin-test aws-iam-authenticator ./ 'aws-iam-authenticator version' --asdf-tool-version v0.4.0
os:
  - linux
  - osx
